# Generated by Django 2.2.6 on 2019-10-27 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PollID', models.DecimalField(decimal_places=0, max_digits=10)),
                ('CandidateName', models.CharField(max_length=100)),
            ],
        ),
    ]
