# Generated by Django 2.2.6 on 2019-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='CandidateName',
        ),
        migrations.RemoveField(
            model_name='data',
            name='PollID',
        ),
        migrations.AddField(
            model_name='data',
            name='answer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='candidate_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='fte_grade',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='office_type',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='party',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pct',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='poll_id',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pollster',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pollster_id',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='pollster_rating_id',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='question_id',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='sample_size',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='stage',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='state',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
