# Generated by Django 2.2.6 on 2019-12-03 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_auto_20191027_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='General_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('candidate_name', models.CharField(max_length=50)),
                ('pct', models.DecimalField(decimal_places=0, max_digits=8)),
            ],
        ),
        migrations.AlterField(
            model_name='data',
            name='pct',
            field=models.DecimalField(decimal_places=0, max_digits=8, null=True),
        ),
    ]
