# Generated by Django 2.2.6 on 2019-12-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0003_auto_20191203_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general_data',
            name='pct',
            field=models.DecimalField(decimal_places=1, max_digits=8),
        ),
    ]
